# based on https://raw.githubusercontent.com/EOSIO/eos/master/Docker/docker-compose-dawn3.0.yaml
version: "3"

    # docker run --rm -d --name eosio -p 8888:8888 -p 9876:9876 -v /tmp/work:/work -v /tmp/eosio/data:/mnt/dev/data -v /tmp/eosio/config:/mnt/dev/config eosio/eos-dev  /bin/bash -c "nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console
services:
  eosio:
    hostname: eosio
    container_name: eosio
    image: eosio/eos-dev
    command: nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console
    ports:
      - "8888:8888"
      - "9876:9876"
    expose:
      - "8888"
    volumes:
      - /tmp/work:/work
      - /tmp/eosio/data:/mnt/dev/data
      - /tmp/eosio/config:/mnt/dev/config
      - ${PWD}/config.ini:/mnt/dev/config/config.ini

  # builder:
  #   image: eosio/builder:latest
  #   command: sleep infinity
  #   hostname: builder
  #   links:
  #     - eosio
  #   volumes:
  #     - ${PWD}/playground:/playground
  #     - ${PWD}/bashrc:/bashrc
