#!/bin/bash

cd /work
alias cleos='/opt/eosio/bin/cleos --url http://nodeos:8888 --wallet-url http://localhost:8900'
alias cleostestnet='/opt/eosio/bin/cleos --url http://dev.cryptolions.io:38888 "$@"'
export PS1="\W $ "
echo "EOS Dev environment ready!"

## Insert here your startup commands
# ..

